### ISSUE TITLE
Fix check for empty value for PHP < 5.5

### ISSUE THREAD

**Issue by zhuravel** [talkable/talkable-magento#1]
In
- /app/design/frontend/base/default/template/talkable/socialreferrals/dashboard.phtml
- /app/design/frontend/base/default/template/talkable/socialreferrals/invite.phtml
- /app/design/frontend/base/default/template/talkable/socialreferrals/post_purchase.phtml

replace `<?php if (empty($_helper->getSiteId())): ?>`
with `<?php if ($_helper->getSiteId() == ""): ?>`

**Comment by bogdan** [comment]
lol!
